spring.application.name=notification-service
# Databasanslutning/ Fixa dessa credentials frï¿½n den andra Java klassen som gjort CRUD-API eller ska vi gï¿½ra egna?
# PostgreSQL kï¿½r pï¿½ port: 5432 normalt och localhost fï¿½r spring boot ï¿½r ju port: 8080
spring.datasource.url=jdbc:postgresql://${HOST}:${PORT}/zoplanner 
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

# Hibernate-instï¿½llningar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Visa SQL-frï¿½gor (utvecklingslï¿½ge)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Anvï¿½nder Port 8081 fï¿½r att undvika konflikt med CRUD-API (port 8080), om det ï¿½r fel kom gï¿½rna med input
server.port=8081

# AWS Konfiguration(Fylls i senare nï¿½r vi har skapat dem tjï¿½nsterna pï¿½ AWS)
# AWS Region (Stockholm)
aws.region=eu-north-1

# AWS SQS - Queue URL vart CRUD-API/Affï¿½rslogik postar events
aws.sqs.queue.url=

# AWS SNS - Topic ARN fï¿½r email notifikationer
aws.sns.topic.email=

# AWS SNS - Topic ARN fï¿½r SMS notifikationer
aws.sns.topic.sms=

## Valfritt att ï¿½ndra dem 3 sista aws punkterna om ni har ett bï¿½ttre sï¿½tt :)

# Var loggarna ska sparas (docker)
notification.audit.log-file=/app/notification-logs/notification.log
# Om det körs lokalt kan man använda:  notification.audit.log-file=notification-logs/notifications.log
